-- Tactical Server User Setup
-- Configures database users and permissions

-- Connect to each database and set up permissions
\c tactical_location;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO tactical;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO tactical;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO tactical;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO tactical;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO tactical;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO tactical;

\c tactical_maps;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO maps_user;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO maps_user;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO maps_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO maps_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO maps_user;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO maps_user;

\c outline;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO outline;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO outline;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO outline;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO outline;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO outline;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO outline;

\c mattermost;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO mattermost;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO mattermost;
GRANT EXECUTE ON ALL FUNCTIONS IN SCHEMA public TO mattermost;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO mattermost;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO mattermost;
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT EXECUTE ON FUNCTIONS TO mattermost;

-- Log completion
\echo 'User permissions setup completed successfully'